Add ignored patches feature to PaStA
lfd/PaStA pull request #32
Opened 2019-09-30 16:40 UTC by 8sd

This pull request adds a feature to detect ignored patches.
In addition, the pull request contains a feature to export the characteristics of the patches analyzed.

2019-10-01 00:21 UTC, rralf requested changes
Could you please squash those changes to the patch "Add script to evaluate patches"?

2019-10-01 00:22 UTC, rralf commented
... And please rebase to latest next. Otherwise, things look fine. Thanks!

2019-10-01 12:25 UTC, 8sd commented
@rralf I did both tasks

2019-10-01 12:35 UTC, merged

2019-10-01 12:36 UTC, rralf commented
Thanks, applied.

2019-10-02 11:54 UTC, rralf commented on bin/pasta_evaluate_patches.py
> +=======
Huh? How did that happen? Will remove this chunk and rewrite next.