pypasta: config: change default filename for cluster output
lfd/PaStA pull request #50
Opened 2020-04-04 08:14 UTC by rsarky

The default filename for both patch stack and mbox mode is same now

Signed-off-by: Rohit Sarkar <rohitsarkar5398@gmail.com>

2020-04-04 17:17 UTC, rralf requested changes
Almost :-) Just one last simplification, then I'll integrate it. Thanks!

2020-04-04 17:17 UTC, rralf commented on pypasta/Config.py
> +        cluster_dst = 'PATCH_GROUPS'
One last thing: You can use 'PATCH_GROUPS' directly below. There's no need for outsourcing it in a variable.

2020-04-04 17:17 UTC, rralf commented on pypasta/Config.py
>          self.f_clustering = path(cluster_dst)
Just use path('PATCH_GROUPS')

2020-04-04 17:59 UTC, rsarky commented on pypasta/Config.py
>          self.f_clustering = path(cluster_dst)
yup makes sense

2020-04-04 18:30 UTC, rralf commented
Thanks, applied!

2020-04-04 18:30 UTC, merged

2020-04-04 18:31 UTC, rralf commented
Ah crap, that was a bit too fast: Could you please forward the resources submodule?

2020-04-04 18:53 UTC, rsarky commented
Sure! Will do once the PR is merged there.

2020-04-04 18:54 UTC, rralf commented
It is merged.

2020-04-05 07:55 UTC, rsarky commented
[This](https://github.com/lfd/PaStA-resources/pull/2) isnt merged yet